#     _____ __            _       __
#    / ___// /____  __   | |     / /___ ___________     __
#    \__ \/ //_/ / / /   | | /| / / __ `/ ___/ ___/  __/ /_
#   ___/ / ,< / /_/ /    | |/ |/ / /_/ / /  (__  )  /_  __/
#  /____/_/|_|\__, /     |__/|__/\__,_/_/  /____/    /_/
#            /____/
# By MyNameIsKiyoshi (Kiyoshi#1010) Updated For 1.19.2 Use JDK 18
Version: 20.37a

# Lang (IT - EN)
Lang: IT
