name: SkyWarsPlus
version: '20.37a'
main: fur.kiyoshi.skywarsplus.Main
api-version: 1.16
authors: [ MyNameIsKiyoshi ]
description: Addon For SkyWars | Add More Functions For SkyWars
commands:
  skyore:
    description: "Open SkyWarsPlus Ore Gui"
